"""Fix Base import and schema

Revision ID: 50942cf39f6a
Revises: 
Create Date: 2025-02-01 23:23:28.100337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50942cf39f6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_table_id', table_name='test_table')
    op.drop_index('ix_test_table_name', table_name='test_table')
    op.drop_table('test_table')
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.drop_constraint('unique_user_response', 'responses', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('unique_user_response', 'responses', ['user_id'])
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_index('ix_test_table_name', 'test_table', ['name'], unique=False)
    op.create_index('ix_test_table_id', 'test_table', ['id'], unique=False)
    # ### end Alembic commands ###
