"""Add profile picture and prompts

Revision ID: 743dca2e48e5
Revises: 50942cf39f6a
Create Date: 2025-02-02 21:05:01.219114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743dca2e48e5'
down_revision: Union[str, None] = '50942cf39f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prompt1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prompt2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prompt3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'prompt3')
    op.drop_column('users', 'prompt2')
    op.drop_column('users', 'prompt1')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
