"""Add bio, prompts, and profile picture

Revision ID: cb6cc5b121e3
Revises: 743dca2e48e5
Create Date: 2025-02-02 21:07:01.937256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6cc5b121e3'
down_revision: Union[str, None] = '743dca2e48e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
